MATPLOTLIB_STYLE = "fivethirtyeight"
MIN_POINTS_TO_FIT = 30
RANDOM_STATE = 3142
TEST_PROPORTION = 0.2
MAX_ODOMETER = 300000
RESIDUAL_FACTOR_DIFF = 1
MANUFACTURERS = [
    "acura",
    "bmw",
    "jaguar",
    "honda",
    "kia",
    "chevrolet",
    "toyota",
    "nissan",
    "volkswagen",
    "ford",
    "gmc",
    "subaru",
    "ram",
    "lexus",
    "volvo",
    "dodge",
    "buick",
    "jeep",
    "hyundai",
    "mercedes-benz",
    "cadillac",
    "audi",
    "infiniti",
    "pontiac",
    "chrysler",
    "rover",
    "mazda",
    "mini",
    "mercury",
    "fiat",
    "tesla",
    "harley-davidson",
    "saturn",
    "mitsubishi",
    "lincoln",
    "alfa-romeo",
    "aston-martin",
    "ferrari",
    "datsun",
    "porche",
    "land rover",
    "hennessey",
]
YEARS = [x for x in range(1981, 2019)]
