MATPLOTLIB_STYLE = "fivethirtyeight"
MIN_POINTS_TO_FIT = 20
RANDOM_STATE = 3142
TEST_PROPORTION = 0.2
MAX_ODOMETER = 300000
RESIDUAL_FACTOR_DIFF = 1
MANUFACTURERS = [
    "acura",
    "bmw",
    "jaguar",
    "honda",
    "kia",
    "chevrolet",
    "toyota",
    "nissan",
    "volkswagen",
    "ford",
    "gmc",
    "subaru",
    "ram",
    "lexus",
    "volvo",
    "dodge",
    "buick",
    "jeep",
    "hyundai",
    "mercedes-benz",
    "cadillac",
    "audi",
    "infiniti",
    "pontiac",
    "chrysler",
    "rover",
    "mazda",
    "mini",
    "mercury",
    nan,
    "fiat",
    "tesla",
    "harley-davidson",
    "saturn",
    "mitsubishi",
    "lincoln",
    "alfa-romeo",
    "aston-martin",
    "ferrari",
    "datsun",
    "porche",
    "land rover",
    "hennessey",
]
MODELS = [
    "mountaineer",
    "outback",
    "sonata",
    "g35",
    "yukon",
    "model s",
    "traverse",
    "124 spider lusso",
    "xc90",
    "sportage",
    "accord lx-s coupe 2d",
    "335",
    "edge",
    "frontier",
    "beetle",
    "tl",
    "town car",
    "grand prix",
    "200",
    "ats",
    "liberty",
]
YEARS = [x for x in range(1981, 2019)]
